mastodon.status_post(status="Record Safari is now playing at the Coachella Stage. #Coachella", scheduled_at=datetime.fromtimestamp(1682088621.0)) 
mastodon.status_post(status="Record Safari has finished playing at the Coachella Stage. Record Safari played from 2:50 PM to 3:25 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682090714.0)) 
mastodon.status_post(status="Doechii is now playing at the Coachella Stage. #Coachella", scheduled_at=datetime.fromtimestamp(1682091011.0)) 
mastodon.status_post(status="Doechii has finished playing at the Coachella Stage. Doechii played from 3:30 PM to 4:10 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682093421.0)) 
mastodon.status_post(status="Pusha T is now playing at the Coachella Stage. #Coachella", scheduled_at=datetime.fromtimestamp(1682094626.0)) 
mastodon.status_post(status="Pusha T has finished playing at the Coachella Stage. Pusha T played from 4:30 PM to 5:15 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682097304.0)) 
mastodon.status_post(status="Becky G is now playing at the Coachella Stage. #Coachella", scheduled_at=datetime.fromtimestamp(1682099127.0)) 
mastodon.status_post(status="Becky G has finished playing at the Coachella Stage. Becky G played from 5:45 PM to 6:30 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682101825.0)) 
mastodon.status_post(status="Burna Boy is now playing at the Coachella Stage. #Coachella", scheduled_at=datetime.fromtimestamp(1682103903.0)) 
mastodon.status_post(status="Burna Boy has finished playing at the Coachella Stage. Burna Boy played from 7:05 PM to 7:55 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682106901.0)) 
mastodon.status_post(status="Gorillaz is now playing at the Coachella Stage. #Coachella", scheduled_at=datetime.fromtimestamp(1682109306.0)) 
mastodon.status_post(status="Gorillaz has finished playing at the Coachella Stage. Gorillaz played from 8:35 PM to 9:50 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682113806.0)) 
mastodon.status_post(status="Juicewon is now playing at the Outdoor Theater. #Coachella", scheduled_at=datetime.fromtimestamp(1682082025.0)) 
mastodon.status_post(status="Juicewon has finished playing at the Outdoor Theater. Juicewon played from 1:00 PM to 2:20 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682086818.0)) 
mastodon.status_post(status="The Comet Is Coming is now playing at the Outdoor Theater. #Coachella", scheduled_at=datetime.fromtimestamp(1682087411.0)) 
mastodon.status_post(status="The Comet Is Coming has finished playing at the Outdoor Theater. The Comet Is Coming played from 2:30 PM to 3:15 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682090115.0)) 
mastodon.status_post(status="Saba is now playing at the Outdoor Theater. #Coachella", scheduled_at=datetime.fromtimestamp(1682091914.0)) 
mastodon.status_post(status="Saba has finished playing at the Outdoor Theater. Saba played from 3:45 PM to 4:25 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682094326.0)) 
mastodon.status_post(status="YUNGBLUD is now playing at the Outdoor Theater. #Coachella", scheduled_at=datetime.fromtimestamp(1682096117.0)) 
mastodon.status_post(status="YUNGBLUD has finished playing at the Outdoor Theater. YUNGBLUD played from 4:55 PM to 5:40 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682098814.0)) 
mastodon.status_post(status="SG Lewis is now playing at the Outdoor Theater. #Coachella", scheduled_at=datetime.fromtimestamp(1682100619.0)) 
mastodon.status_post(status="SG Lewis has finished playing at the Outdoor Theater. SG Lewis played from 6:10 PM to 7:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682103609.0)) 
mastodon.status_post(status="Kaytranada is now playing at the Outdoor Theater. #Coachella", scheduled_at=datetime.fromtimestamp(1682105426.0)) 
mastodon.status_post(status="Kaytranada has finished playing at the Outdoor Theater. Kaytranada played from 7:30 PM to 8:30 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682109015.0)) 
mastodon.status_post(status="Jim Smith is now playing at Sonora. #Coachella", scheduled_at=datetime.fromtimestamp(1682078418.0)) 
mastodon.status_post(status="Jim Smith has finished playing at Sonora. Jim Smith played from 12:00 PM to 1:10 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682082616.0)) 
mastodon.status_post(status="The Murder Capital is now playing at Sonora. #Coachella", scheduled_at=datetime.fromtimestamp(1682082619.0)) 
mastodon.status_post(status="The Murder Capital has finished playing at Sonora. The Murder Capital played from 1:10 PM to 1:40 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682084409.0)) 
mastodon.status_post(status="Lava La Rue is now playing at Sonora. #Coachella", scheduled_at=datetime.fromtimestamp(1682085611.0)) 
mastodon.status_post(status="Lava La Rue has finished playing at Sonora. Lava La Rue played from 2:00 PM to 2:35 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682087714.0)) 
mastodon.status_post(status="Soul Glo is now playing at Sonora. #Coachella", scheduled_at=datetime.fromtimestamp(1682088927.0)) 
mastodon.status_post(status="Soul Glo has finished playing at Sonora. Soul Glo played from 2:55 PM to 3:25 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682090728.0)) 
mastodon.status_post(status="DannyLux is now playing at Sonora. #Coachella", scheduled_at=datetime.fromtimestamp(1682091626.0)) 
mastodon.status_post(status="DannyLux has finished playing at Sonora. DannyLux played from 3:40 PM to 4:20 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682094023.0)) 
mastodon.status_post(status="Magdalena Bay is now playing at Sonora. #Coachella", scheduled_at=datetime.fromtimestamp(1682095819.0)) 
mastodon.status_post(status="Magdalena Bay has finished playing at Sonora. Magdalena Bay played from 4:50 PM to 5:35 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682098521.0)) 
mastodon.status_post(status="TV Girl is now playing at Sonora. #Coachella", scheduled_at=datetime.fromtimestamp(1682099719.0)) 
mastodon.status_post(status="TV Girl has finished playing at Sonora. TV Girl played from 5:55 PM to 6:40 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682102420.0)) 
mastodon.status_post(status="Sasha Alex Sloan is now playing at Sonora. #Coachella", scheduled_at=datetime.fromtimestamp(1682106006.0)) 
mastodon.status_post(status="Sasha Alex Sloan has finished playing at Sonora. Sasha Alex Sloan played from 7:40 PM to 8:20 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682108428.0)) 
mastodon.status_post(status="Desert Cahuilla Bird Singers is now playing at Gobi. #Coachella", scheduled_at=datetime.fromtimestamp(1682081129.0)) 
mastodon.status_post(status="Desert Cahuilla Bird Singers has finished playing at Gobi. Desert Cahuilla Bird Singers played from 12:45 PM to 1:10 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682082626.0)) 
mastodon.status_post(status="Juipter & Okwess is now playing at Gobi. #Coachella", scheduled_at=datetime.fromtimestamp(1682083224.0)) 
mastodon.status_post(status="Juipter & Okwess has finished playing at Gobi. Juipter & Okwess played from 1:20 PM to 2:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682085612.0)) 
mastodon.status_post(status="¿Téo? is now playing at Gobi. #Coachella", scheduled_at=datetime.fromtimestamp(1682086823.0)) 
mastodon.status_post(status="¿Téo? has finished playing at Gobi. ¿Téo? played from 2:20 PM to 2:55 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682088917.0)) 
mastodon.status_post(status="Gabriels is now playing at Gobi. #Coachella", scheduled_at=datetime.fromtimestamp(1682090429.0)) 
mastodon.status_post(status="Gabriels has finished playing at Gobi. Gabriels played from 3:20 PM to 4:05 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682093122.0)) 
mastodon.status_post(status="Overmono is now playing at Gobi. #Coachella", scheduled_at=datetime.fromtimestamp(1682094326.0)) 
mastodon.status_post(status="Overmono has finished playing at Gobi. Overmono played from 4:25 PM to 5:15 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682097305.0)) 
mastodon.status_post(status="Tobe Nwigwe is now playing at Gobi. #Coachella", scheduled_at=datetime.fromtimestamp(1682099113.0)) 
mastodon.status_post(status="Tobe Nwigwe has finished playing at Gobi. Tobe Nwigwe played from 5:45 PM to 6:35 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682102114.0)) 
mastodon.status_post(status="Yves Tumor is now playing at Gobi. #Coachella", scheduled_at=datetime.fromtimestamp(1682103912.0)) 
mastodon.status_post(status="Yves Tumor has finished playing at Gobi. Yves Tumor played from 7:05 PM to 7:50 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682106615.0)) 
mastodon.status_post(status="The Garden is now playing at Gobi. #Coachella", scheduled_at=datetime.fromtimestamp(1682108115.0)) 
mastodon.status_post(status="The Garden has finished playing at Gobi. The Garden played from 8:15 PM to 9:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682110821.0)) 
mastodon.status_post(status="Whyte Fang is now playing at Gobi. #Coachella", scheduled_at=datetime.fromtimestamp(1682112328.0)) 
mastodon.status_post(status="Whyte Fang has finished playing at Gobi. Whyte Fang played from 9:25 PM to 10:15 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682115320.0)) 
mastodon.status_post(status="Black Jade is now playing at Mojave. #Coachella", scheduled_at=datetime.fromtimestamp(1682080214.0)) 
mastodon.status_post(status="Black Jade has finished playing at Mojave. Black Jade played from 12:30 PM to 1:30 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682083818.0)) 
mastodon.status_post(status="Lewis OfMan is now playing at Mojave. #Coachella", scheduled_at=datetime.fromtimestamp(1682084425.0)) 
mastodon.status_post(status="Lewis OfMan has finished playing at Mojave. Lewis OfMan played from 1:40 PM to 2:15 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682086512.0)) 
mastodon.status_post(status="Domi & JD Beck is now playing at Mojave. #Coachella", scheduled_at=datetime.fromtimestamp(1682088007.0)) 
mastodon.status_post(status="Domi & JD Beck has finished playing at Mojave. Domi & JD Beck played from 2:40 PM to 3:20 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682090401.0)) 
mastodon.status_post(status="BENEE is now playing at Mojave. #Coachella", scheduled_at=datetime.fromtimestamp(1682091913.0)) 
mastodon.status_post(status="BENEE has finished playing at Mojave. BENEE played from 3:45 PM to 4:25 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682094309.0)) 
mastodon.status_post(status="MUNA is now playing at Mojave. #Coachella", scheduled_at=datetime.fromtimestamp(1682095817.0)) 
mastodon.status_post(status="MUNA has finished playing at Mojave. MUNA played from 4:50 PM to 5:35 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682098510.0)) 
mastodon.status_post(status="Wet Leg is now playing at Mojave. #Coachella", scheduled_at=datetime.fromtimestamp(1682100028.0)) 
mastodon.status_post(status="Wet Leg has finished playing at Mojave. Wet Leg played from 6:00 PM to 6:45 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682102722.0)) 
mastodon.status_post(status="Blondie is now playing at Mojave. #Coachella", scheduled_at=datetime.fromtimestamp(1682105718.0)) 
mastodon.status_post(status="Blondie has finished playing at Mojave. Blondie played from 7:35 PM to 8:35 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682109317.0)) 
mastodon.status_post(status="Angèle is now playing at Mojave. #Coachella", scheduled_at=datetime.fromtimestamp(1682111410.0)) 
mastodon.status_post(status="Angèle has finished playing at Mojave. Angèle played from 9:10 PM to 9:55 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682114104.0)) 
mastodon.status_post(status="Mary Jane is now playing at Sahara. #Coachella", scheduled_at=datetime.fromtimestamp(1682084727.0)) 
mastodon.status_post(status="Mary Jane has finished playing at Sahara. Mary Jane played from 1:45 PM to 3:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682089224.0)) 
mastodon.status_post(status="Dombresky is now playing at Sahara. #Coachella", scheduled_at=datetime.fromtimestamp(1682089814.0)) 
mastodon.status_post(status="Dombresky has finished playing at Sahara. Dombresky played from 3:10 PM to 4:05 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682093109.0)) 
mastodon.status_post(status="Malaa is now playing at Sahara. #Coachella", scheduled_at=datetime.fromtimestamp(1682093719.0)) 
mastodon.status_post(status="Malaa has finished playing at Sahara. Malaa played from 4:15 PM to 5:10 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682097007.0)) 
mastodon.status_post(status="Vintage Culture is now playing at Sahara. #Coachella", scheduled_at=datetime.fromtimestamp(1682097611.0)) 
mastodon.status_post(status="Vintage Culture has finished playing at Sahara. Vintage Culture played from 5:20 PM to 6:15 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682100902.0)) 
mastodon.status_post(status="Blink-182 is now playing at Sahara. #Coachella", scheduled_at=datetime.fromtimestamp(1682102711.0)) 
mastodon.status_post(status="Blink-182 has finished playing at Sahara. Blink-182 played from 6:45 PM to 7:35 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682105704.0)) 
mastodon.status_post(status="Jamie Jones is now playing at Sahara. #Coachella", scheduled_at=datetime.fromtimestamp(1682107507.0)) 
mastodon.status_post(status="Jamie Jones has finished playing at Sahara. Jamie Jones played from 8:05 PM to 8:55 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682110512.0)) 
mastodon.status_post(status="Two Friends is now playing at Sahara. #Coachella", scheduled_at=datetime.fromtimestamp(1682112011.0)) 
mastodon.status_post(status="Two Friends has finished playing at Sahara. Two Friends played from 9:20 PM to 10:05 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682114710.0)) 
mastodon.status_post(status="Juliet Mendoza is now playing at Yuma. #Coachella", scheduled_at=datetime.fromtimestamp(1682078406.0)) 
mastodon.status_post(status="Juliet Mendoza has finished playing at Yuma. Juliet Mendoza played from 12:00 PM to 1:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682082021.0)) 
mastodon.status_post(status="Chris Stussy is now playing at Yuma. #Coachella", scheduled_at=datetime.fromtimestamp(1682082019.0)) 
mastodon.status_post(status="Chris Stussy has finished playing at Yuma. Chris Stussy played from 1:00 PM to 2:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682085626.0)) 
mastodon.status_post(status="Kyle Watson is now playing at Yuma. #Coachella", scheduled_at=datetime.fromtimestamp(1682085622.0)) 
mastodon.status_post(status="Kyle Watson has finished playing at Yuma. Kyle Watson played from 2:00 PM to 3:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682089219.0)) 
mastodon.status_post(status="Oliver Koletzki is now playing at Yuma. #Coachella", scheduled_at=datetime.fromtimestamp(1682089202.0)) 
mastodon.status_post(status="Oliver Koletzki has finished playing at Yuma. Oliver Koletzki played from 3:00 PM to 4:15 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682093728.0)) 
mastodon.status_post(status="Dennis Cruz + PAWSA is now playing at Yuma. #Coachella", scheduled_at=datetime.fromtimestamp(1682093714.0)) 
mastodon.status_post(status="Dennis Cruz + PAWSA has finished playing at Yuma. Dennis Cruz + PAWSA played from 4:15 PM to 5:30 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682098222.0)) 
mastodon.status_post(status="Nora En Pure is now playing at Yuma. #Coachella", scheduled_at=datetime.fromtimestamp(1682098214.0)) 
mastodon.status_post(status="Nora En Pure has finished playing at Yuma. Nora En Pure played from 5:30 PM to 6:45 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682102715.0)) 
mastodon.status_post(status="Idris Elba is now playing at Yuma. #Coachella", scheduled_at=datetime.fromtimestamp(1682102701.0)) 
mastodon.status_post(status="Idris Elba has finished playing at Yuma. Idris Elba played from 6:45 PM to 8:15 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682108115.0)) 
mastodon.status_post(status="Mochakk is now playing at Yuma. #Coachella", scheduled_at=datetime.fromtimestamp(1682108105.0)) 
mastodon.status_post(status="Mochakk has finished playing at Yuma. Mochakk played from 8:15 PM to 9:45 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682113516.0)) 
mastodon.status_post(status="TESTPILOT is now playing at Yuma. #Coachella", scheduled_at=datetime.fromtimestamp(1682113502.0)) 
mastodon.status_post(status="TESTPILOT has finished playing at Yuma. TESTPILOT played from 9:45 PM to 11:15 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682118904.0)) 
mastodon.status_post(status="Bones is now playing at Heineken House. #Coachella", scheduled_at=datetime.fromtimestamp(1682078403.0)) 
mastodon.status_post(status="Bones has finished playing at Heineken House. Bones played from 12:00 PM to 2:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682085604.0)) 
mastodon.status_post(status="Lee Wells is now playing at Heineken House. #Coachella", scheduled_at=datetime.fromtimestamp(1682085601.0)) 
mastodon.status_post(status="Lee Wells has finished playing at Heineken House. Lee Wells played from 2:00 PM to 4:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682092802.0)) 
mastodon.status_post(status="Hannah Wants is now playing at Heineken House. #Coachella", scheduled_at=datetime.fromtimestamp(1682092807.0)) 
mastodon.status_post(status="Hannah Wants has finished playing at Heineken House. Hannah Wants played from 4:00 PM to 6:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682100003.0)) 
mastodon.status_post(status="Walker & Royce is now playing at Heineken House. #Coachella", scheduled_at=datetime.fromtimestamp(1682100010.0)) 
mastodon.status_post(status="Walker & Royce has finished playing at Heineken House. Walker & Royce played from 6:00 PM to 8:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682107205.0)) 
mastodon.status_post(status="Felix Da Housecat is now playing at Heineken House. #Coachella", scheduled_at=datetime.fromtimestamp(1682107212.0)) 
mastodon.status_post(status="Felix Da Housecat has finished playing at Heineken House. Felix Da Housecat played from 8:00 PM to 10:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682114423.0)) 
mastodon.status_post(status="Andreas One is now playing at Do LaB. #Coachella", scheduled_at=datetime.fromtimestamp(1682078405.0)) 
mastodon.status_post(status="Andreas One has finished playing at Do LaB. Andreas One played from 12:00 PM to 1:30 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682083817.0)) 
mastodon.status_post(status="Michaël Brun is now playing at Do LaB. #Coachella", scheduled_at=datetime.fromtimestamp(1682083816.0)) 
mastodon.status_post(status="Michaël Brun has finished playing at Do LaB. Michaël Brun played from 1:30 PM to 2:40 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682088022.0)) 
mastodon.status_post(status="Bresh is now playing at Do LaB. #Coachella", scheduled_at=datetime.fromtimestamp(1682088002.0)) 
mastodon.status_post(status="Bresh has finished playing at Do LaB. Bresh played from 2:40 PM to 4:10 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682093422.0)) 
mastodon.status_post(status="Bambii is now playing at Do LaB. #Coachella", scheduled_at=datetime.fromtimestamp(1682093717.0)) 
mastodon.status_post(status="Bambii has finished playing at Do LaB. Bambii played from 4:15 PM to 5:15 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682097329.0)) 
mastodon.status_post(status="Mr. Carmack is now playing at Do LaB. #Coachella", scheduled_at=datetime.fromtimestamp(1682097610.0)) 
mastodon.status_post(status="Mr. Carmack has finished playing at Do LaB. Mr. Carmack played from 5:20 PM to 6:20 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682101228.0)) 
mastodon.status_post(status="The Glitch Mob is now playing at Do LaB. #Coachella", scheduled_at=datetime.fromtimestamp(1682101512.0)) 
mastodon.status_post(status="The Glitch Mob has finished playing at Do LaB. The Glitch Mob played from 6:25 PM to 7:25 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682105100.0)) 
mastodon.status_post(status="Whipped Cream is now playing at Do LaB. #Coachella", scheduled_at=datetime.fromtimestamp(1682105127.0)) 
mastodon.status_post(status="Whipped Cream has finished playing at Do LaB. Whipped Cream played from 7:25 PM to 8:25 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682108726.0)) 
mastodon.status_post(status="(SURPRISE) is now playing at Do LaB. #Coachella", scheduled_at=datetime.fromtimestamp(1682109026.0)) 
mastodon.status_post(status="(SURPRISE) has finished playing at Do LaB. (SURPRISE) played from 8:30 PM to 9:50 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682113800.0)) 
mastodon.status_post(status="Flight Facilities DJ set is now playing at Do LaB. #Coachella", scheduled_at=datetime.fromtimestamp(1682113803.0)) 
mastodon.status_post(status="Flight Facilities DJ set has finished playing at Do LaB. Flight Facilities DJ set played from 9:50 PM to  11:00 PM. #coachella", scheduled_at=datetime.fromtimestamp(1682118022.0)) 
mastodon.status_post(status="(SURPRISE) is now playing at Do LaB. #Coachella", scheduled_at=datetime.fromtimestamp(1682118004.0)) 
mastodon.status_post(status="(SURPRISE) has finished playing at Do LaB. (SURPRISE) played from 11:00 PM to  1:00 AM. #coachella", scheduled_at=datetime.fromtimestamp(1682038811.0)) 
